#!/bin/env bash
# shellcheck disable=SC2035

if [ -z "$GITHUB_WORKSPACE" ]; then
	echo "This script should only run on GitHub action!" >&2
	exit 1
fi

# Make sure we're on right directory
cd "$GITHUB_WORKSPACE" || {
	echo "Unable to cd to GITHUB_WORKSPACE" >&2
	exit 1
}

# Version info
version="$(cat version)"
version_code="$(git rev-list HEAD --count)"
release_code="$(git rev-list HEAD --count)-$(git rev-parse --short HEAD)-release"
sed -i "s/version=.*/version=$version ($release_code)/" module/module.prop
sed -i "s/versionCode=.*/versionCode=$version_code/" module/module.prop

# Point the module manager (Magisk / KernelSU / APatch) at this repository's update manifest.
# It polls this URL, compares versionCode against the installed module, and offers a direct
# download + install. `releases/latest` always resolves to the newest published release, so the
# field never needs updating. Derived from GITHUB_REPOSITORY so a fork advertises its own
# releases instead of someone else's.
sed -i "s|updateJson=.*|updateJson=https://github.com/$GITHUB_REPOSITORY/releases/latest/download/update.json|" module/module.prop

# The `support` key is where MMRL and WebUI X send a user who taps "Support" on the module card.
# Derived from GITHUB_REPOSITORY for the same reason updateJson is: a fork must point at its own
# issue tracker, not at this one, or its users file bugs against a build nobody here shipped.
sed -i "s|support=.*|support=https://github.com/$GITHUB_REPOSITORY/issues|" module/module.prop

# `donate` is written only when an official destination is configured. It is deliberately not a
# committed default: an unset, wrong, or member-only URL on a donation button is worse than no
# button, because the user cannot tell a broken link from a project that does not accept support.
# See module/installer/config.sh for the single place this value is defined.
OFFICIAL_DONATION_URL="$(sed -n 's/^OFFICIAL_DONATION_URL=//p' module/installer/config.sh | tr -d "\"'")"
if [ -n "$OFFICIAL_DONATION_URL" ]; then
	case "$OFFICIAL_DONATION_URL" in
	https://*)
		printf 'donate=%s\n' "$OFFICIAL_DONATION_URL" >>module/module.prop
		printf 'donateIcon=donate.webp\n' >>module/module.prop
		echo "Donate metadata enabled: $OFFICIAL_DONATION_URL"
		;;
	*)
		echo "OFFICIAL_DONATION_URL must be an https:// URL, got: $OFFICIAL_DONATION_URL" >&2
		exit 1
		;;
	esac
else
	echo "No OFFICIAL_DONATION_URL configured; donate metadata omitted (this is not an error)."
fi

# Copy module files
cp -r ./libs module

# Only the device runtime scripts ship. scripts/ also holds CI/development tooling
# (fetch-synthesiscore, verify-synthesiscore, update-synthesiscore-lock) which has no meaning on
# a device: customize.sh never installs it, so copying everything only padded the zip with dead
# tooling. This is an allowlist on purpose — a new script has to be named here to ship, rather
# than reaching users because it happened to land in the directory.
# flux_utility is the only runtime script left. flux_profiler.sh was the legacy shell applier
# and is gone: the V2 ExecutionEngine applies profiles, and packaging a script nothing can invoke
# would leave a working copy of the old write path on every device for someone to run by hand.
# This was a loop over both; a loop over one entry is just a copy.
cp ./scripts/flux_utility.sh module/system/bin/ || {
	echo "Missing runtime script: scripts/flux_utility.sh" >&2
	exit 1
}
cp gamelist.txt module
cp LICENSE module
cp NOTICE.md module

# Branding assets live under module/assets/, which is the editable source and is NOT packaged: it
# also holds the SVG sources, and a device has no use for those. Each asset is copied to the flat,
# module-root path its metadata key names.
#
# The donate icon is generated by scripts/render-icons.py. The banner is not — it is a conversion
# of a maintainer-approved artwork, and scripts/verify-branding.py pins its decoded identity.
#
# There is no action or webui icon: no official Flux emblem exists, so module.prop sets neither
# `actionIcon` nor `webuiIcon` and each manager draws its own default. Copying a stand-in here
# would put artwork on the module card that the project has not approved as its identity.
#
# The paths are flat on purpose. `banner` and `donateIcon` are resolved by the module manager
# relative to the module root, and manager support for a *nested* asset path is not uniform across
# Magisk / KernelSU / APatch / MMRL. A file at the root resolves everywhere that resolves it at
# all, so the packaged layout stays flat even though the source tree is not.
for asset in \
	"assets/branding/banner.webp:banner.webp" \
	"assets/icons/donate.webp:donate.webp"; do
	src="module/${asset%%:*}"
	dst="module/${asset##*:}"
	[ -f "$src" ] || {
		echo "Missing branding asset: $src" >&2
		echo "Icons regenerate with: python3 scripts/render-icons.py" >&2
		echo "The banner is converted from the maintainer-approved source; it is not generated." >&2
		exit 1
	}
	cp "$src" "$dst"
done

find ./prebuilt -mindepth 1 -maxdepth 1 ! -name "README.md" -exec cp -r {} ./module \;
find ./config -mindepth 1 -maxdepth 1 ! -name "README.md" -exec cp -r {} ./module/config \;

# Remove .sh extension from scripts
find module/system/bin -maxdepth 1 -type f -name "*.sh" -exec sh -c 'mv -- "$0" "${0%.sh}"' {} \;

# Parse version info to module prop
zipName="flux-$version-$release_code.zip"
echo "zipName=$zipName" >>"$GITHUB_OUTPUT"

# Generate sha256sum for integrity checkup
bash .github/scripts/gen_sha256sum.sh "module"

cd ./module || {
	echo "Unable to cd to ./module" >&2
	exit 1
}

# Zip the file.
#
# assets/ is excluded: it is the editable source for the branding (including SVGs), and the
# rasters it produces were already copied to the flat module-root paths module.prop names.
# Shipping both would put two copies of every banner and icon on the device, and the SVG sources
# have no consumer there at all.
zip -r9 ../"$zipName" * -x *placeholder* *.map .shellcheckrc "assets/*"
zip -z ../"$zipName" <<EOF
$version-$release_code
Build Date $(date +"%a %b %d %H:%M:%S %Z %Y")
EOF
